### ISSUE TITLE
-

### ISSUE THREAD

**Issue by a02172af717d06d116dc5a62386de345d4d9790** [joyn-gg/discord.http#2]
-

**Comment by AlexFlipnote** [comment]
Ayy, will look into this when I can

**Comment by AlexFlipnote** [comment]
Done, you can view the version that supports it here:
🔗 https://github.com/joyn-gg/discord.http/releases/tag/1.3.8

Also if you need an example on how to use it, visit this example:
🔗 https://github.com/joyn-gg/discord.http/blob/master/examples/user_command_example.py
